databases:
  - name: db_kjewel
    databaseName: kjdb
    user: kjdb_user

services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: postgres://kjdb_user:qaU7tTMiUhynzkVsJ1aei8ZB4qwmAo3V@dpg-c646n546fj31g6t68og0/kjdb
        fromDatabase:
          name: db_kjewel
          property: connectionString
      - key: django-insecure-j5crf+@6@y#5*ik&-mtz*wo70*$pawrjh!281t@w@u*&6ug_pi
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4